// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package models

import (
	"database/sql"
	"encoding/json"
)

type CompanyBalance struct {
	ID        int64  `json:"id"`
	CompanyID int64  `json:"company_id"`
	Balance   string `json:"balance"`
}

type CompanyBalanceTransaction struct {
	ID         int64           `json:"id"`
	CompanyID  int64           `json:"company_id"`
	Type       int32           `json:"type"`
	Amount     int64           `json:"amount"`
	Data       json.RawMessage `json:"data"`
	SenderType int32           `json:"sender_type"`
	SenderID   sql.NullInt64   `json:"sender_id"`
	ProviderID int32           `json:"provider_id"`
	Status     int32           `json:"status"`
	IsInit     bool            `json:"is_init"`
	PaidAt     sql.NullTime    `json:"paid_at"`
}

type CompanyCart struct {
	ID         int64         `json:"id"`
	CompanyID  int64         `json:"company_id"`
	SenderType int32         `json:"sender_type"`
	SenderID   sql.NullInt64 `json:"sender_id"`
	ProviderID int32         `json:"provider_id"`
	Status     int32         `json:"status"`
	Sum        string        `json:"sum"`
	PaidAt     sql.NullTime  `json:"paid_at"`
}

type CompanyCartService struct {
	ID            int64 `json:"id"`
	CompanyCartID int64 `json:"company_cart_id"`
	ServiceID     int64 `json:"service_id"`
}

type CompanyService struct {
	ID            int64          `json:"id"`
	CompanyID     int64          `json:"company_id"`
	ServiceID     int64          `json:"service_id"`
	HashCode      sql.NullString `json:"hash_code"`
	EmployeeID    int64          `json:"employee_id"`
	Amount        string         `json:"amount"`
	Discount      string         `json:"discount"`
	ItemLimit     sql.NullInt32  `json:"item_limit"`
	EmployeeLimit sql.NullInt32  `json:"employee_limit"`
	StockLimit    sql.NullInt32  `json:"stock_limit"`
	ExtraStockID  sql.NullInt64  `json:"extra_stock_id"`
	ActivatedAt   sql.NullTime   `json:"activated_at"`
	ExpiresAt     sql.NullTime   `json:"expires_at"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type Service struct {
	ID            int64         `json:"id"`
	Title         string        `json:"title"`
	Price         string        `json:"price"`
	Type          int32         `json:"type"`
	Month         sql.NullInt32 `json:"month"`
	IsTis         bool          `json:"is_tis"`
	IsVisible     bool          `json:"is_visible"`
	ItemLimit     sql.NullInt32 `json:"item_limit"`
	EmployeeLimit sql.NullInt32 `json:"employee_limit"`
	StockLimit    sql.NullInt32 `json:"stock_limit"`
	DeletedAt     sql.NullTime  `json:"deleted_at"`
}
