// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: transactions.sql

package models

import (
	"context"
	"database/sql"
)

const createTransaction = `-- name: CreateTransaction :execresult
insert into company_balance_transactions(
    company_id,    type,    sender_type,
    sender_id,    amount,    status,    provider_id
) values (
    ?,?,?,?,?,?,?
)
`

type CreateTransactionParams struct {
	CompanyID  int64         `json:"company_id"`
	Type       int32         `json:"type"`
	SenderType int32         `json:"sender_type"`
	SenderID   sql.NullInt64 `json:"sender_id"`
	Amount     int64         `json:"amount"`
	Status     int32         `json:"status"`
	ProviderID int32         `json:"provider_id"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTransaction,
		arg.CompanyID,
		arg.Type,
		arg.SenderType,
		arg.SenderID,
		arg.Amount,
		arg.Status,
		arg.ProviderID,
	)
}
