// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	CompanyBalanceTransactions string
	CompanyBalances            string
	CompanyCartServices        string
	CompanyCarts               string
	CompanyServices            string
	SchemaMigrations           string
	Services                   string
}{
	CompanyBalanceTransactions: "company_balance_transactions",
	CompanyBalances:            "company_balances",
	CompanyCartServices:        "company_cart_services",
	CompanyCarts:               "company_carts",
	CompanyServices:            "company_services",
	SchemaMigrations:           "schema_migrations",
	Services:                   "services",
}
